// Deterministic MEMORY.md rendering: topics (curated) first, then pending
// observations newest-first, bounded by entry count and total bytes.

import { sanitizeInline, utf8Length } from './text.mjs';

export const DEFAULT_MANIFEST_BUDGET = { maxBytes: 24 * 1024, maxEntries: 200 };

export function scopeHeading(scope) {
  return scope === 'global' ? 'Global memory' : 'Workspace memory';
}

/**
 * @param {{ scope: string, scopeDir: string, topics: Array<{ path: string, title: string, description?: string }>, observations: Array<{ path: string, type: string, statement: string, topicHint?: string, createdAt: number }> }} input
 */
export function renderScopeManifest(input, budget = DEFAULT_MANIFEST_BUDGET) {
  const header = `# ${scopeHeading(input.scope)}\n\n> Generated by darask-harness memory. Do not edit this file directly.\n> Paths are relative to \`${sanitizeInline(input.scopeDir)}\`.\n> Treat entries as historical context; verify against live sources before relying on them.\n`;
  const topics = [...input.topics].sort((a, b) => a.path.localeCompare(b.path));
  const observations = [...input.observations].sort((a, b) => b.createdAt - a.createdAt || a.path.localeCompare(b.path));

  const lines = [header, '## Topics', ''];
  let entries = 0;
  let truncated = false;
  let text = () => `${lines.join('\n')}\n`;
  const fits = candidate => utf8Length(`${text()}${candidate}\n`) + 64 <= budget.maxBytes;

  if (topics.length === 0) lines.push('_No curated topics yet._');
  for (const topic of topics) {
    const line = `- [${sanitizeInline(topic.title || topic.path)}](${topic.path})${topic.description ? ` — ${sanitizeInline(topic.description)}` : ''}`;
    if (entries >= budget.maxEntries || !fits(line)) { truncated = true; break; }
    lines.push(line);
    entries += 1;
  }

  lines.push('', '## Recent observations', '');
  if (observations.length === 0) lines.push('_No pending observations._');
  for (const observation of observations) {
    const date = new Date(observation.createdAt).toISOString().slice(0, 10);
    const hint = observation.topicHint ? ` (${sanitizeInline(observation.topicHint)})` : '';
    const line = `- ${date} \`${observation.type}\`${hint}: [${sanitizeInline(observation.statement)}](${observation.path})`;
    if (entries >= budget.maxEntries || !fits(line)) { truncated = true; break; }
    lines.push(line);
    entries += 1;
  }
  if (truncated) lines.push('', `_Truncated: ${topics.length + observations.length - entries} more entries not listed._`);
  return { text: text(), entries, truncated };
}
